server {
    listen 80;
    server_name symfony.test;
    root /var/www/html/public; # Symfony's public directory

    # Add security headers (optional but recommended)
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    location / {
        # Try to serve file directly, fallback to Symfony Front Controller
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm:9000; # Link to PHP-FPM service
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    location ~ /\.ht {
        deny all;
    }
}

# HTTPS server block
server {
    listen 443 ssl;
    server_name symfony.test;
    root /var/www/html/public;

    # SSL Configuration
    ssl_certificate /etc/nginx/certs/symfony.test.crt;
    ssl_certificate_key /etc/nginx/certs/symfony.test.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    ssl_client_certificate /etc/nginx/certs/mTLS/ca.crt;
    ssl_verify_client on;

    location / {
        fastcgi_param SSl_CLIENT_S_DN $ssl_client_s_dn;
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php-fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}