; Example custom PHP settings
memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
date.timezone = UTC ; Essential for Symfony

; Increase Xdebug memory limit if needed
; xdebug.max_nesting_level = 512